### PR TITLE
Fix the wiki bug preventing page list display to observers other than…

### PR DESCRIPTION
**Pull request by anaqreon**
… the channel owner.

**This pull request is not tested yet, and there might be other things to do like bump the version number before it is merged.**

I pulled these updates from commit 7562f77bdf7040d5cc63473a3c6ff7c499600f13.

### CODE REVIEW

**Comment by git-marijus** [comment]
@anaqreon that is not the (exact) commit from me... What else did you change?

**Comment by anaqreon** [comment]
I think there was a blank line deletion that I merged from the current dev version of one of the files.

**Comment by git-marijus** [comment]
Hm... I see other changes aswell and i am not sure where they come from.

**Comment by git-marijus** [comment]
https://github.com/redmatrix/hubzilla/commit/7562f77bdf7040d5cc63473a3c6ff7c499600f13 that is my commit in dev branch for comparison.

**Comment by anaqreon** [comment]
I must have been in too much of a rush. I'll review it later and get back to you.

**Comment by anaqreon** [comment]
This time the cherry-pick worked, even though it's the same commit I used before... Anyway, I was able to test it and it appears to fix the wiki page list issue in master. I bumped the STD_VERSION to 2.4.1.

**Pull request closed without merging**
