### PR TITLE
Upgrade PHP Markdown library.

### PR DESCRIPTION
**Pull request by dawnbreak**
The current version throws deprecated warning with PHP7.1 and PHPUnit.
Upgrade the Markdown library to the current PHP Markdown Lib 1.7.0.

### CODE REVIEW

**Comment by zotlabs** [comment]
@dawnbreak could you have a look at the travis error this threw? It appears there might be an unmet  phpunit dependency. If this is resolved by the pull request that's great, but you're a bit more equipped to determine this.

**Comment by dawnbreak** [comment]
PHP feels more and more like Ruby with all it's dependency hell.
I hope after this PR my Travis PR will also work finally. That should also have fixed the build error.

**Comment by dawnbreak** [comment]
I just saw we had modifications in the old library. I need bit more examples to test this with.
Also when I take a look at markdown_to_bb() do you have example texts you used to test this function with?

**Comment by zotlabs** [comment]
There are no existing markdown tests. I see two changes that might be worth keeping, but perhaps we should move them to a wrapper. I don't believe either will cause any serious bugs. One allowed for inline (span) code blocks as opposed to div blocks. The other allowed underscores in HTML tag names and I can't really recall why we needed this back in 2011 other than the fact that HTML4|5 are a bit more permissive than earlier versions in this regard. I would expect this has long been fixed upstream.  If it's possible to keep the original commits (perhaps git move the library file to retain the history) I'm happy to upgrade and we can decide if we need to add these changes back in or put them into wrappers.

**Pull request merged**
