### PR TITLE
fixes for wiki create/delete page

### PR DESCRIPTION
**Pull request by git-marijus**
This pullrequest addresses three issues:
1. Creating a new page failed because `post_activity_item()` did not return anything if `$deliver = false`. I changed it to at least return the `$post_id` which we need to proceed...

2. Deleting a page failed because we tried to create a commit for the already deleted item. I stripped away the commit part (could probably commit before deletion but the page was deleted anyway there is no need for the commit).

3. The pagelist widget returned "(No Title)" items for deleted pages. I added `and item_hidden = 0` to the query.

Please review!

### CODE REVIEW

**Comment by zotlabs** [comment]
From your description of number 3, I'm unclear on why item_hidden should be involved. Should this perhaps be item_deleted ?

Thanks for the catch on post_activity_item with $deliver = false.  I may refine that a bit further to also return the activity item but nothing depends on it today.

**Comment by git-marijus** [comment]
>From your description of number 3, I'm unclear on why item_hidden should be involved. 

I also thought so but was proved wrong... That might indicate another bug somewhere though...

**Comment by zotlabs** [comment]
I will investigate

**Comment by git-marijus** [comment]
Another thing regarding deletion: We should probably restrict deletion of a page to the page owner. It is not possible otherwise to find out who deleted the page (since we got no commit) and it is probably irreversible atm.

**Comment by zotlabs** [comment]
I restricted deletion

turns out the item_hidden is because of historical usage of photo linked items, so all linked items are marked hidden rather than deleted. Ultimately the items should all be deleted regardless of whether or not they are linked to other data but sorting it out is a job for another day.

**Pull request merged**
