### PR TITLE
allow multiple-file cloud upload

### PR DESCRIPTION
**Pull request by git-marijus**

### CODE REVIEW

**Comment by redmatrix** [comment]
I have a couple of concerns. The first is that this will not allow us to set an ACL on the resultant files (that's why I created the file_upload module); but by far the biggest issue is that this is going to hit memory limitations real fast if you (for instance) select 40-50 full resolution photos. We'll likely have all kinds of bug reports about white screens while uploading. This could also hit filesystem limits on sites where / (which holds /tmp) is on a small partition such as my shared host. 

I can merge this anyway, but we need to deal with these issues and I think it will require bypassing sabre post actions and handling the uploads ourself. For multiple files we need to call an upload daemon process for each one. Perhaps pass it a target directory, filename, and channel_id. That should be enough to create a standalone uploader. 

For the filesystem limits, there is a config for js_upload which uses a definable tmpdir; not sure how this is done without a php.ini setting. but if we can't configure it directly, we probably need to document how to modify it. 

For ACLs was thinking this morning to duplicate what you did for the permissions and create the HTML block for uploading in the filestorage module and ajax-load and switch it in and out like you do for each file edit block.

**Comment by git-marijus** [comment]
I see... I reverted this change in favour of @anaqreon's implementation... It makes use of the browsers file upload api and opens a post request for each file and is therefor maybe easier on memory or can at least probably be throttled (uploading only one after another)... 
Regarding ACL i think sooner or later we should make it work with different forms per site... Have not looked into it but it seems like a heavy change...Moving ACL around with jquery is probably a good workaraound and sufficient for the time beeing... Not sure on the long term though...

**Comment by redmatrix** [comment]
The ACL functions themselves seem built for multiple instances. I think it's mostly the integration between the tool and HTML where it's breaking (e.g. using named #id targets rather than .class targets). I think that while it's desirable to have multiple independent ACL selectors on a page, we could also probably find an easy way to share a single ACL selector amongst multiple forms on the page; so if you wanted to add a single channel to an access list you could just do it once and submit it for multiple items.

**Comment by git-marijus** [comment]
> I think that while it's desirable to have multiple independent ACL selectors on a page, we could also probably find an easy way to share a single ACL selector amongst multiple forms on the page; so if you wanted to add a single channel to an access list you could just do it once and submit it for multiple items.

Nice idea... We would than have to submit multiple forms in one action i guess...

**Pull request merged**
