### PR TITLE
Pdo DB driver

### PR DESCRIPTION
**Pull request by zotlabs**
replace mysqli and postgres db drivers with PDO. Moderately tested with mysqli and postgres installations. Using mysql in Unix domain socket configuration was not attempted and isn't supported automatically. To do this one needs to change their db_server configuration variable to the precise DSN needed by PDO.  For instance "mysql:unix_socket=/tmp/mysql.sock;" The db name will be added automatically.

### CODE REVIEW

**Comment by dawnbreak** [comment]
Tested it on a local only dev environment. Haven't seen exceptions or new errors yet. The old drivers can be removed and the name in the log statements was first confusing, as it still said dba_mysqli.
How you want to hand over the PDO connection also to the other parts that already implemented pdo as you said? Something like \DBA::$dba->getPDO(); where getPDO returns $db from dba_driver?

**Comment by zotlabs** [comment]
I have two concerns. The first is my implementation of pg_(un)escape_bytea functions; which could affect existing photos on postgres if they are wrong. I'll try to do a bit more testing of this but it may require my postgres install, which is at work and I can't really get to until Monday.  If somebody here is able, perhaps encode a string containing nuls, backslashes, and single quotes using pg_escape_bytea() and see if stripcslashes() will get the original string back.  

My second concern is folks using Unix domain sockets instead of TCP with MySQL. This may be automatic if they setup their site with 'localhost' as the server name; and I'm not certain how to auto-convert them. We may in fact need to translate 'localhost' to the PDO DSN for sockets within the driver. This is something I cannot easily test. The alternative may be hand-holding when this goes live to let people know how to fix their config file. 

As for passing the DB connection to CalDAV, I plan to bring the Cdav plugin into core and eventually merging with our events system. This isn't something I'm going to worry about today. On the short term I want to move forward with PDO, breaking as little as possible and then extend it as time goes on.

**Comment by zotlabs** [comment]
Yeah, hold off on this. The postgres binary escaping/unescaping turns out to be somewhat of a nightmare to implement.

**Comment by zotlabs** [comment]
I should probably close this request, but basically it needs somebody with strong postgres fu to sort out. 
The two issues noted above have been resolved. Remaining is a new issue that the pdo driver returns bytea fields as streams and not as strings. This requires a fair bit of code refactoring to read from the streams and convert them with dbunesc and eventually return the actual data strings to the application. I will leave this open for the time being. If it does not get resolved in a reasonable period of time, the request will be closed and/or postgres MAY be deprecated and eventually removed as being unsupportable.

**Comment by zotlabs** [comment]
OK, all issues should be resolved, but we need some testing with postgres photos/files before this can be merged.

**Comment by zotlabs** [comment]
ok, here goes...

**Pull request merged**
