### PR TITLE
Comment and code about UTF-8 @-sign do not match.

### PR DESCRIPTION
**Pull request by dawnbreak**
Changed code according to comment:
First AT is now full-width AT U+FF20.
Do we also need to replace small AT U+FE6B?

What for is this needed?
Can someone check this PR if the desired behaviour is still true.

### CODE REVIEW

**Comment by zotlabs** [comment]
I cannot see any reason why this line would be necessary here. @anaqreon ?

**Comment by anaqreon** [comment]
I'm sure I was just copying code, so if it doesn't make sense to you Mike, then it isn't necessary.

**Comment by anaqreon** [comment]
Now I remember whence I copied this code: https://github.com/redmatrix/hubzilla/blob/master/Zotlabs/Module/Follow.php#L24

**Comment by zotlabs** [comment]
It once made sense there, but has been deprecated. We shouldn't be seeing pasted webbies from the profile page inside cloud filepaths. In any event we're now just replacing them with htmlentities. I'll go ahead and merge this and then remove it.

**Pull request merged**
