### PR TITLE
add querystring to css and js which is added via head_add_{css, js}

### PR DESCRIPTION
**Pull request by git-marijus**
this will prevent caching problems on std_version updates

### CODE REVIEW

**Comment by git-marijus** [comment]
Anyone has concerns about this?
It is not perfect since we refresh all css and js files on std_version bump even they did not change... OTOH since we have a master and a dev branch now this will not happen so often in master...

**Comment by redmatrix** [comment]
No concerns, I've just been too busy to look closely. I do like the etag concept but don't know what it would take to integrate. If you're happy with this, please merge it. I've got some issues with github atm or I would do so.

**Comment by anaqreon** [comment]
Yeah I don't see how forcing a refresh occasionally can hurt.

**Comment by git-marijus** [comment]
I investigated a little regarding the querystring vs the etag concept and found the results quite polarizing... So i'd say for now stick with the querystring solution...

**Pull request merged**
