### PR TITLE
Configuring email notifications per channel

### PR DESCRIPTION
**Pull request by ilu33**
#578

### CODE REVIEW

**Comment by zotlabs** [comment]
Closing since this won't really work.

**Comment by ilu33** [comment]
I'm not sure you understood what I wanted to do: I wanted to have a tool to set notifications to OFF because members are complaining about too many notifications and prefer to delete their channel instead of configuring it - and we want them to keep it. Or are you saying that disabling notifications that way does not work?
I would eliminate the part that tried to use "notification_on" because that was something I did not really think about. I could instead print that to turn notifications on you need to use the GUI.

Could you reopen the pull request?

**Comment by ilu33** [comment]
This got somehow out of hand, I'm still struggling with git. Sorry.

**Comment by git-marijus** [comment]
I think this merge borked some things... I got a broken db upgrade...

**Comment by git-marijus** [comment]
Nevermind, it's probably not related to this merge.

**Pull request merged**
