### PR TITLE
Translationfr

### PR DESCRIPTION
**Pull request by chris1315**

### CODE REVIEW

**Comment by git-marijus** [comment]
There are still huge chunks of english text in those files. Mind to translate them also?

**Comment by chris1315** [comment]
what shall I do. I just want to translate the help page. Did I do mistake ?

**Comment by git-marijus** [comment]
It appears to me that only a small part of the content you pushed ist translated to french. The majority is still english...

**Comment by chris1315** [comment]
OK I understand now. Yes I should work faster. All is not finished but I wanted to be sure how to use git first . Now I think I see the begining of the work. I will work more....

**Comment by git-marijus** [comment]
I will close this for now. Please reopen when ready.

**Pull request closed without merging**
