### PR TITLE
[TASK] Fix travis' phpunit execution.

### PR DESCRIPTION
**Pull request by dawnbreak**

### CODE REVIEW

**Comment by dawnbreak** [comment]
Not working... don't merge yet.

**Comment by dawnbreak** [comment]
php5.5 still fails. It has nothing to do with hubzilla, it is because the used phpunit requires php>=5.6.

**Comment by zotlabs** [comment]
Might take this up with the community. 5.5 is end of life now. I know there is still a redmatrix site stuck with a 5.3 cli ; but I think most of the rest of us may be OK with a 5.6 requirement.

**Comment by dawnbreak** [comment]
This PR should now pass travis. Removed PHP 5.4 and 5.5 from test matrix as they have reached EOL and our tests do not tell anything about hubzilla's compatibility with these PHP versions anyway.

**Comment by zotlabs** [comment]
So it's ok to merge?

**Comment by dawnbreak** [comment]
yes.

**Pull request merged**
