### PR TITLE
Change Add Apps to Manage Apps and support translation.

### PR DESCRIPTION
**Pull request by anaqreon**

### CODE REVIEW

**Comment by zotlabs** [comment]
Hmmm. This one has me in a quandary. I actually think that 'Add Apps' is the better description given the now critical role of this in accessing the site and site features/components.

Many people looking at this menu dropdown aren't interested in managing anything. They just want to navigate to somewhere on the site. If the location they want isn't there, they would probably consider adding it.  

However, if it is to be "Manage Apps" we probably should do away with the plus symbol. I'd probably wait for @git-marijus for advice. Though I agree it should be translate-able. No problem there.

**Comment by anaqreon** [comment]
It's probably not worth over-analyzing. I wanted to capture that it's an "add" _and_ an "edit" button, but "Add/Edit Apps" looked too clunky. I also think "Select Apps" might be okay.

**Comment by zotlabs** [comment]
Select works for me and I don't have a problem with that appearing next to a plus sign. I'd still give Mario the final word.

**Comment by git-marijus** [comment]
The only reason this link is there is to provide a possibility to "Add" new apps to the tray. Anything else would be completely misleading. I kindly ask you to keep it that way.

When clicking that link at first you can't manage, edit or select anything. You can add or remove apps to the bin. For any other action you have to click through to edit or create.

**Comment by zotlabs** [comment]
OK I'm going to pull it so we get the other fix and then change the words back.

**Comment by git-marijus** [comment]
Thanks

**Pull request merged**
