### PR TITLE
Updated Spanish strings for Hubzilla

### PR DESCRIPTION
**Pull request by mjfriaza**

### CODE REVIEW

**Comment by jeroenpraat** [comment]
Why did you create this request? I didn't had time to commit the strings to github yet, but they are already on yout hub.

**Comment by jeroenpraat** [comment]
Now it's committed.

**Comment by mjfriaza** [comment]
It wanted to learn to do it by me same :-)

**Comment by jeroenpraat** [comment]
Ah OK. Did you edited hstrings.php by hand? If so, it's better to generate that file with util/po2php.php on a real up-to-date Hubzilla hub. In the past I also did it by hand and it gave easily issues. So please let me or someone else with a hub do it.

**Comment by mjfriaza** [comment]
"Did you edited hstrings.php by hand?"

No by hand but with:

php util/po2php.php view/es/hmessages.po

and I check hstrings.php for errors:

php view/es/hstrings.php

**Comment by jeroenpraat** [comment]
Do you have your own hub now? If so, I didn't say anything.

**Comment by mjfriaza** [comment]
No, I do not have. Only my github fork. But I want to have it in a future ;-)

**Pull request closed without merging**
