### PR TITLE
HTMLPurifier library update

### PR DESCRIPTION
**Pull request by dawnbreak**
Updated HTML Purifier from 4.6.0 to 4.9.2 with better PHP7 compatibility.
Used composer to manage this library.

I could need some help testing this PR, as it is used in several parts of the system like wiki, feeds, oembed, etc.

### CODE REVIEW

**Comment by dawnbreak** [comment]
Don't merge yet, found an error I need to fix first.

**Comment by dawnbreak** [comment]
We should deal with PR #702 first and add some more HTML examples to test against changes with this library update.

**Comment by zotlabs** [comment]
@dawnbreak I have a separate branch with some experimental work and my normal dev server won't run composer for a variety of reasons. In that branch I've moved library/oauth2 to composer.

"bshaffer/oauth2-server-php": "~1.8"

This involved copying everything to another system where I could run composer and then bringing it back again. A bit of a hassle. 

Could I get you to also make this change in the dev branch so we don't get into merge hell with composer.lock between the mentioned branches? There are no internal dependencies (yet) on the library involved so no code changes or testing is required.

I'm probably not the best person to write the HTML tests as my own work just requires basic javascript filtering which uses the default html-purifier rules. @git-marijus may be able to provide something to test the webpage creation with stuff like bootstrap and foundation.

**Comment by dawnbreak** [comment]
Created a PR for oauth2 (#703 ).

**Comment by dawnbreak** [comment]
I add some more asserts in the test case today, but not sure what else I should test. So how to continue?

**Comment by git-marijus** [comment]
Is this ready for merge now?

**Pull request merged**
