### PR TITLE
Help setting

### PR DESCRIPTION
**Pull request by anaqreon**
Added setting to /admin/site for disabling the context help button. Access to help would be via the /apps page if disabled.

### CODE REVIEW

**Comment by redmatrix** [comment]
A bit concerned about this - as it is ostensibly described as disabling *context* help, but in reality disables *all* help and makes one work to get it back. Is there no way to disable context help in isolation? Or perhaps I'm not following the reasoning behind this.

**Comment by anaqreon** [comment]
Funny thing is that originally I started making an "enable_context_help" setting and then got to include/nav.php:152 and saw that there was already an "if(! hide_help)" statement in there, so it looked like someone had already made the config parameter with the goal of completely hiding the help button. So I changed my config parameter to match and thought the idea was that if you didn't want context help, then you don't need the big shiny persistent help button in the navbar. 

We could either (1) go with my original intention and simply change the help button behavior to either display context help or go straight to the docs, or (2) keep the current implementation and add a persistent link to the docs in the user dropdown menu on the left.

**Comment by jeroenpraat** [comment]
I also have my doubts. The request to have this as a setting was that members and admins can choose the old behavior without context help. Disabling the help button completely doesn't sound as a good idea.

**Comment by anaqreon** [comment]
Okay I'll implement (1) when I have a chance, or someone else can do it if they want it sooner.

**Comment by redmatrix** [comment]
It's all coming back now. I seem to recall the original config was because of a complaint that somebody didn't want to see English help; and it wasn't translated to their language, so they wanted nothing. So I withdraw my concern, but I do think that (1) is what I expected to see in this pull request.

**Comment by anaqreon** [comment]
To do this I need to take the JavaScript out of redbasic.js and put it back in nav.tpl so that I can surround the script with an {{If}} block that only loads the help panel launch if the setting is enabled. Is there a better way to implement system config dependent JavaScript?

**Comment by git-marijus** [comment]
you can set a global JS variable in head.tpl instead...

**Comment by anaqreon** [comment]
So the distinction is that you don't want the JavaScript in template files to actually _do_ anything directly, but it's acceptable that they set variable values which may or may not be used elsewhere?

**Comment by git-marijus** [comment]
I try to avoid it if possible... In some cases we have seperate templates for javascript... See for example jot...

**Comment by anaqreon** [comment]
I'm creating a new updated pull request.

**Pull request closed without merging**
