### PR TITLE
installation script for debian next to a router at home

### PR DESCRIPTION
**Pull request by einervonvielen**
This is a script for an unattended installation of hubzilla on a debian that is connected to a router at home.

It works with two dynamic IP services, freeDNS and selfHOST.

The hub digitalesparadies.de was completely installed by it.

It uses let's encrypt for certifactes. Iinstead of the official client of letsencrypt a a shell script is used to create and renew the certificates, see https://github.com/lukas2511/letsencrypt.sh.

The script aims to automate as much as possible, including
- daily backups (using rsnapshot) (certificates are backed up as well)
- daily updates of Debian, hubzilla, letsencypt-script
- renewal of letsencrypt certificates
- dynamic IP udates (freeDNS or selfHOST), poller,php

The only thing that is not automated is a restore from the backups if something crashes (db, debian, pc,....). 

The hub admin can watch all daily backups and updates in a log that is written to /var/www/html/hubzilla-daily.log and can be viewed under "Administration" > "Protocols" > "Protocol file = hubzilla-daily.log".
The log will also show some stats on
- size of hubzilla db
- free disk space of internal disk and external backup devices
- renewed certificates
- ...

The script is attended for a hub admin with only very basic knowledge and should automate everything for him. 

The main goal is to install new hubs for friends, colleagues, may be in schools, something like this. Scripted unattended installations might help to have kind of standard installations that are not as error prone as manual installations and might be easier to trouble shoot. 

WATCH THIS 
A had to delete and commit "view/es" in order to branch and push my changes. I did not know another solution to get rid of the error messages. Hmm, sorry for this if this makes any trouble.

### CODE REVIEW

**Comment by einervonvielen** [comment]
This line is wrong in the readme,md:

> ++ Copy hubzilla-config.txt and hubzilla-setup.sh to your Debian (future hub)

Can (will) be deleted if I add more text to the readme.md

**Comment by jeroenpraat** [comment]
Looks great. But why do you had to delete view/es? It's a symlink to es-es and it makes sure Spanish speakers outside Spain have Hubzilla in Spanish (until a regional translation is ready). What kind of error message do you receive?

**Comment by einervonvielen** [comment]
@jeroenpraat I could not get  rid of error messages caused by "view/es". I did a fresh git clone several times using empty directories and then tried to create a branch. And I had always error messages about unstaged files  "view/es" I have nothing to do with. Don't know where this came from.

**Comment by einervonvielen** [comment]
I do not want to delete anything ( "view/es"). Found not way out of the error messages other than deleting.

**Comment by jeroenpraat** [comment]
Yes, but what is exactly the error message?

**Comment by einervonvielen** [comment]
There are unstaged files ( "view/es"."). Please commit them first... Something like this.

My pull request has nothing to do with them.

**Comment by einervonvielen** [comment]
If you know how to get the pull request into the repository without touching those  "view/es"...?

**Comment by einervonvielen** [comment]
Git did not let me branch before fixing the unstaged  "view/es".

I did
> git clone https://github.com/redmatrix/hubzilla/ html 
 
before I tried to create a (local) branch.

**Comment by jeroenpraat** [comment]
OK, there are many ways to fix this, but the most easiest way is that @redmatrix merges your commit first and I put the symlink back afterwards.

**Comment by einervonvielen** [comment]
Yes indeed.

( It's a bit of a shame for me that I could not manage this git stuff myself ;-(  Hmm.)

**Pull request merged**
