### PR TITLE
New Portfolio widget for DEV

### PR DESCRIPTION
**Pull request by HaakonME**
The Portfolio widget presents images as framed thumbnails linked to a modal with a larger version. If a caption for an image is provided, it will be displayed when hovering over the thumbnail, and when the thumbnail is clicked the modal will go to fullscreen, showing a larger version of the image with the caption as a heading. 

It is hoped this widget's output is slim enough to allow its flexible inclusion in different webpage layouts.

Files:
Zotlabs/Widget/Portfolio.php
view/tpl/photo_album_portfolio.tpl
view/tpl/photo_portfolio.tpl

### CODE REVIEW

**Comment by zotlabs** [comment]
include/widgets.php was included in this pull request and it is no longer used. This could create a huge merge issue.

**Comment by HaakonME** [comment]
Right, I forgot about that. How can I fix it? Just pull the latest version of that file, then do it again?

**Comment by zotlabs** [comment]
The most foolproof method would probably be to fetch the entire tree fresh and then add back your local changes.

**Comment by HaakonME** [comment]
Thanks, will do.

**Comment by HaakonME** [comment]
Right, I have done
```
git remote update
git reset --hard upstream/dev --
git push origin +dev
```

then copied in the original files and

```
git add Zotlabs/Widget/Portfolio.php 
git add view/tpl/photo_album_portfolio.tpl 
git add view/tpl/photo_portfolio.tpl 
git commit -am "Added Portfolio widget"
git push origin
```
so hopefully this will work this time.

**Comment by zotlabs** [comment]
That looks much better.

**Comment by git-marijus** [comment]
Thanks and welcome to the club @HaakonME 👍 
I will merge this. I wonder if this will probably not work so well without the foundation library. You should probably document that somewhere.

**Pull request merged**
