### PR TITLE
issue 1154 fix

### PR DESCRIPTION
**Pull request by zlaxy**
https://github.com/redmatrix/hubzilla/issues/1154 - The call to a function z_dns_check() with the second parameter only occurs from function validate_email(). So the added condition is logically suitable for this check.

### CODE REVIEW

**Comment by zotlabs** [comment]
I don't have a BSD system available at this time, so unable to verify. There are some comments on the web that the dns tools work in recent BSD releases, but many of the comments are from 4-5 years ago when they clearly did not.

**Comment by zotlabs** [comment]
I've just pushed an alternate fix which scrapes the platform and reacts to all the known variations of behaviour.

**Comment by zlaxy** [comment]
@zotlabs I tested registration on my hub just now with last dev updates - it's still `500 Internal Server Error` on my server. Please point me to your pushed alternate fix.

**Comment by zotlabs** [comment]
````
function z_dns_check($h,$check_mx = 0) {

    // dns_get_record() has issues on some platforms
    // so allow somebody to ignore it completely
    // Use config values from memory as this can be called during setup
    // before a database or even any config structure exists.

    if(is_array(\App::$config) && array_key_exists('system',\App::$config)
        && is_array(\App::$config['system'])
        && array_key_exists('do_not_check_dns',\App::$config['system'])
        && \App::$config['system']['do_not_check_dns'])
        return true;

    // This will match either Windows or Mac ('Darwin')
    if(stripos(PHP_OS,'win') !== false)
        return true;

    // BSD variants have dns_get_record() but it only works reliably without any options
    if(stripos(PHP_OS,'bsd') !== false)
        return((@dns_get_record($h) || filter_var($h, FILTER_VALIDATE_IP)) ? true : false);

    // Otherwise we will assume dns_get_record() works as documented

    $opts = DNS_A + DNS_CNAME + DNS_PTR;
    if($check_mx)
        $opts += DNS_MX;

    return((@dns_get_record($h,$opts) || filter_var($h, FILTER_VALIDATE_IP)) ? true : false);
}
````

**Pull request closed without merging**
